import React from 'react'

function Airtags() {
  return (
    <div>
         <Head>
        <title>Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

    </div>
  )
}

export default Airtags