import Head from "next/head"

function Airtags() {
  return (
    <div>
         <Head>
        <title>AirTag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <

    </div>
  )
}

export default Airtags