import Head from "next/head"

function Airtags() {
  return (
    <div >
         <Head>
        <title>AirTag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
        <img src="https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airtag-double-select-202104_FMT_WHH?wid=2000&hei=2000&fmt=jpeg&qlt=90&.v=1617761672000"></img>
     </div>
    </div>
  )
}

export default Airtags