
   
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Apple Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Delete this code to begun coding*/}
      <img className=' h-96 ' src='https://upload.wikimedia.org/wikipedia/commons/8/84/Apple_Computer_Logo_rainbow.svg' ></img>
      <h1>Apple Clone</h1>
      <h2>Made with 💙 by Arjun Joshi</h2>
    </div>
  )
}